== WebFlux + React Demo Steps

=== Spring WebFlux API

. start.spring.io: data-mongodb-reactive, webflux, devtools, and lombok [`webflux-start`]

  http https://start.spring.io/starter.zip dependencies==data-mongodb-reactive,webflux,devtools,lombok -d

. Add `Profile`, `ProfileRepository`, and `SampleDataInitializer` [`webflux-entity`, `webflux-repo`, `webflux-data`]

. Start and see list of profiles in console

. Create `ProfileRestController` with a `/profiles` endpoint [`webflux-controller`]

. Restart server with classic profile: `SPRING_PROFILES_ACTIVE=classic mvn`

. Restart and confirm http://localhost:8080/profiles works in browser and with http

  http POST :8080/profiles email='matt.raible@okta.com'
  http PUT :8080/profiles/1 email='matt.raible@okta.com'
  http DELETE :8080/profiles/1

. Create `ProfileCreatedEvent`, `ProfileCreatedEventPublisher`, and `ProfileService` [`webflux-event, `webflux-publisher`, `webflux-service`]

. Create `ProfileHandler`, `ProfileEndPointConfiguration`, and `CaseInsensitiveRequestPredicate` [`webflux-handler`, `webflux-endpoint`, `webflux-predicate`]

. Restart and confirm http://localhost:8080/profiles works in browser and with http

. Create `WebSocketConfiguration` and `static/ws.html` [`webflux-websocket`, `webflux-ws`]

. Show http://localhost:8080/ws.html and run `create.sh`

. Create `ServerSentEventController`, show `http http://localhost:8080/sse/profiles -S` [`webflux-sse`]

=== React App

. Run `npx create-react-app react-app --scripts-version=react-scripts-ts`; show app with `npm start`

. Modify `App.tsx` and add `componentDidMount()` to fetch profiles [`react-fetch`]

. Create interfaces: `Profile`, `AppProps`, and `AppState`; add constructor and initialize state [`react-constructor`]

. Change `render()` to show profiles [`react-loading` and `react-list`]

. Modify `tslint.json` to fix issues [`tslint-rules`]

. Configure proxy for React and show list of profiles

. Create `ProfileList.tsx` and copy code from `App.tsx`; change `App.tsx` to use `<ProfileList/>`

=== React App with Streaming Data

. Modify `ProfileList.tsx` to fetch every second [`react-interval`]

. Create and run `create-stream.sh`

. Use RxJS: install rxjs first! [`react-rxjs`]

. Use WebSocket [`react-websocket`]

. Use EventSource with SSE [`react-eventsource`]

=== PWA Support

. Run `npm run build`; serve with `serve -s build -p 3000`

. Run Lighthouse; fix 512px icon https://www.flaticon.com [`react-icon`]

=== Authentication with Okta

. Add Spring Security OIDC and dependencies [`ss-maven`]

. Create OIDC app in Okta; add properties to `application.yml` [`ss-application`]

. Create `SecurityConfiguration` for resource server and CORS [`ss-demo`]

. Show login redirect from http://localhost:8080

. Add Okta's React SDK [`okta-react`]

  yarn add @okta/okta-react@1.1.1 react-router-dom@4.3.1
  yarn add -D @types/react-router-dom@4.3.1

. Update `App.tsx` to use `<Security/>` component [`react-security`]

. Create `src/okta.d.ts` with `declare module '@okta/okta-react';`

. Create `Home.tsx` to render the app shell, login/logout buttons, and use `<ProfileList/>` [`react-home`]

. Add CSS to `App.css` to make buttons more visible [`react-css`]

. Show app and Loading...

. Update `ProfileList` to add an authorization header + error handling [`react-token`]

. Modify `WebSocketConfiguration.java` to only return an ID.

. Modify `ProfileList` to fetch a profile by ID when added. [`react-websocket2`]

. Run `./create-stream.sh` and show profiles being added.

. Fini!

Source: https://developer.okta.com/blog/2018/09/24/reactive-apis-with-spring-webflux