== WebFlux + React Demo Steps

=== Spring WebFlux API

. start.spring.io: data-mongodb-reactive, webflux, devtools, and lombok [`webflux-start`]

  http https://start.spring.io/starter.zip dependencies==data-mongodb-reactive,webflux,devtools,lombok -d

. Add `Profile`, `ProfileRepository`, and `SampleDataInitializer` [`webflux-entity`, `webflux-repo`, `webflux-data`]

. Start and see list of profiles in console: `SPRING_PROFILES_ACTIVE=demo mvn`

. Create `ProfileService` [`webflux-service`]

. Create `ProfileRestController` with a `/profiles` endpoint [`webflux-controller`]

. Restart server with classic profile: `SPRING_PROFILES_ACTIVE=classic mvn`

. Restart and confirm http://localhost:8080/profiles works in browser and with http

  http POST :8080/profiles email='matt.raible@okta.com'
  http PUT :8080/profiles/1 email='matt.raible@okta.com'
  http DELETE :8080/profiles/1

. Create `ProfileCreatedEvent`, `ProfileCreatedEventPublisher`, and update `ProfileService` [`webflux-event`, `webflux-publisher`]

. Create `WebSocketConfiguration` for executor bean [`webflux-websocket`]

. Create `ProfileHandler`, `ProfileEndPointConfiguration`, and `CaseInsensitiveRequestPredicate` [`webflux-handler`, `webflux-endpoint`, `webflux-predicate`]

. Restart and confirm http://localhost:8080/profiles works in browser and with http

. Create `static/ws.html` to show event notifications [`webflux-ws`]

. Restore `doOnSuccess` in `ProfileService` and show http://localhost:8080/ws.html with `create.sh`

. Create `ServerSentEventController`, show `http http://localhost:8080/sse/profiles -S` [`webflux-sse`]

=== React App

. Run `npx create-react-app react-app --scripts-version=react-scripts-ts`; show app with `npm start`

. Modify `App.tsx` and add `componentDidMount()` to fetch profiles [`react-fetch`]

. Create interfaces: `Profile`, `AppProps`, and `AppState`; add constructor and initialize state [`react-constructor`]

. Change `render()` to show profiles [`react-loading` and `react-list`]

. Modify `tslint.json` to fix issues [`tslint-rules`]

. Configure proxy for React and show list of profiles [`react-proxy`]

. Create `ProfileList.tsx` and copy code from `App.tsx`; change `App.tsx` to use `<ProfileList/>`

=== React App with Streaming Data

. Modify `ProfileList.tsx` to fetch every second [`react-interval`]

. Create and run `create-stream.sh`

. Use RxJS: install rxjs first! [`react-rxjs`]

. Use WebSocket [`react-websocket`]

. Use EventSource with SSE [`react-eventsource`]

. Add `@CrossOrigin` in `ServerSentEventController`

=== Authentication with Okta

. Add Spring Security OIDC and dependencies [`ss-maven`]

. Create OIDC app in Okta; add properties to `application.yml` [`ss-application`]

. Upgrade Spring Boot to `2.1.0.M4` in `pom.xml` and add snapshot repos [`spring-repos`]

. Show login redirect from http://localhost:8080/profiles

. Create `SecurityConfiguration` for resource server and CORS [`ss-config`]

. Add Okta's React SDK [`okta-react`]

  yarn add @okta/okta-react@1.1.1 react-router-dom@4.3.1
  yarn add -D @types/react-router-dom@4.3.1

. Update `App.tsx` to use `<Security/>` component [`react-security`]

. Create `src/okta.d.ts` with `declare module '@okta/okta-react';`

. Create `Home.tsx` to render the app shell, login/logout buttons, and use `<ProfileList/>` [`react-home`]

. Add CSS to `App.css` to make buttons more visible [`react-css`]

. Remove `proxy` from `package.json`, restart, show app and Loading...

. Update `ProfileList` to add an authorization header + error handling [`react-token`]

. Modify `WebSocketConfiguration.java` to only return an ID.

. Modify `ProfileList` to fetch a profile by ID when added. [`react-websocket2`]

. Run `./create-stream.sh` and show profiles being added.

. Fini!

Source: https://developer.okta.com/blog/2018/09/25/spring-webflux-websockets-react
